### PR TITLE
Added tests for "graded" complexity reports

### PR DESCRIPTION
**Pull request by tiyberius**
Let me know if this works. I refactored the `parse()` method because I thought I needed to in order to write the tests, but then realized that I didn't need to. I left it in because I think it makes the code simpler, but I can take it out if you feel strongly about it. I ran the tests and they all passed, and we've got coverage for the code that I added in my prevous PR.

### CODE REVIEW

**Comment by kinow** [comment]
Thanks @tiyberius ! Will check out the pull request tonight to run the tests locally, but everything looks neat. We'll probably have a new release out in the update center by tomorrow morning :smile:

**Comment by kinow** [comment]
Fixed and release @tiyberius . 

Had to bump up the analysis collector version to use newer Maven and JDK. Can you check if that's working and, if you have spare time, update the CCM Plug-in Wiki, please?

Thanks!

**Comment by tiyberius** [comment]
Hey Bruno,

I updated the wiki but it doesn't appear to have changed. Initially I thought that the change had to be approved by a moderator, but I think I might have just been having network troubles. I'll give it another shot today.

**Comment by kinow** [comment]
No worries @tiyberius . I'm having problems with the Wiki in the past days too. If you want you can chime in in this issue if you are having the same problem - https://issues.jenkins-ci.org/browse/INFRA-300

**Comment by tiyberius** [comment]
So I figured out what happened yesterday. I edited the page, forgot to
enter the CAPTCHA and clicked "Save". When the page reloaded the CAPTCHA, I
didn't notice that the page didn't save my edits. Which is part of what's
described in https://issues.jenkins-ci.org/browse/INFRA-300. Thanks for
pointing that issue out, I'll post a comment on it. Eventually I did edit
the Wiki and the 3.0.2 release should have notes now.

**Comment by kinow** [comment]
Great, thanks a lot @tiyberius !

**Pull request merged**
